version: '3'
services:
  telegram-bot-app:
    container_name: telegram-bot-java
    build: .
    environment:
      - DB_URL=jdbc:postgresql://ps_db:5432/postgres
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
    ports:
      - 8080:8080
    restart: on-failure
    depends_on:
      - ps_db
  ps_db:
    container_name: ps_db
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USERNAME=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    restart: always

